const ExcelJS=require('exceljs'); const PDFDocument=require('pdfkit');
const {Inventory,RawMaterial,Order,Expenses,BalanceSheet}=require('../adapters/coreModels');
class ExportService{
  static flattenObject(obj,prefix='',target={}){ for(const [k,v] of Object.entries(obj||{})){ const out=prefix?`${prefix}.${k}`:k; if(v&&typeof v==='object'&&!Array.isArray(v)&&!(v instanceof Date)) ExportService.flattenObject(v,out,target); else target[out]=Array.isArray(v)?JSON.stringify(v):v instanceof Date?v.toISOString():v; } return target; }
  static async loadTenantData(companyId){ const inventories=await Inventory.find({company_id:companyId}).lean(); const ids=inventories.map(i=>String(i.inventory_id||i._id)); const [rawMaterials,orders,expenses,balanceSheets]=await Promise.all([RawMaterial.find({inventory_id:{$in:ids}}).lean(),Order.find({company_id:companyId}).lean(),Expenses.find({company_id:companyId}).lean(),BalanceSheet.find({company_id:companyId}).lean()]); return {Inventory:inventories,Raw_Materials:rawMaterials,Order:orders,Expenses:expenses,BalanceSheet:balanceSheets}; }
  static async buildXlsx(companyId){ const data=await ExportService.loadTenantData(companyId), wb=new ExcelJS.Workbook(); wb.creator='IN-Track'; for(const [name,rows] of Object.entries(data)){ const ws=wb.addWorksheet(name.slice(0,31)); if(!rows.length){ws.addRow(['No data']);continue;} const flat=rows.map(r=>ExportService.flattenObject(r)), cols=[...new Set(flat.flatMap(r=>Object.keys(r)))]; ws.columns=cols.map(key=>({header:key,key,width:20})); flat.forEach(r=>ws.addRow(r)); } return wb.xlsx.writeBuffer(); }
  static async buildPdf(companyId){ const data=await ExportService.loadTenantData(companyId); return new Promise((resolve,reject)=>{ const chunks=[],doc=new PDFDocument({margin:40}); doc.on('data',c=>chunks.push(c)); doc.on('end',()=>resolve(Buffer.concat(chunks))); doc.on('error',reject); doc.fontSize(18).text('IN-Track Tenant Data Summary',{align:'center'}).moveDown(); doc.fontSize(10).text(`Company ID: ${companyId}`).text(`Generated: ${new Date().toISOString()}`).moveDown(); for(const [name,rows] of Object.entries(data)){doc.fontSize(14).text(name);doc.fontSize(10).text(`Records: ${rows.length}`);rows.slice(0,50).forEach((r,i)=>doc.fontSize(8).text(`${i+1}. ${JSON.stringify(r)}`));doc.moveDown();} doc.end(); }); }
}
module.exports=ExportService;
